[package]
name = "nulltermarrayiter"
description = "Iterator over raw pointer to null-terminated array; for FFI"
version = "0.1.1"
authors = ["Ian Douglas Scott <ian@iandouglasscott.com>"]
repository = "https://github.com/ids1024/nulltermarrayiter-rs"
license = "MIT"
